// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFSVSq7bTsSHhTldoWpp4pMpJbv_vCUk',
    appId: '1:672650725357:web:3e70aa44461f384d6249e4',
    messagingSenderId: '672650725357',
    projectId: 'esp32-rtdb-b9561',
    authDomain: 'esp32-rtdb-b9561.firebaseapp.com',
    databaseURL: 'https://esp32-rtdb-b9561-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-rtdb-b9561.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBlRjWdylSjHmdwzu1AgSbulp4djW1hY',
    appId: '1:672650725357:android:4a452e101d0f0cc66249e4',
    messagingSenderId: '672650725357',
    projectId: 'esp32-rtdb-b9561',
    databaseURL: 'https://esp32-rtdb-b9561-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-rtdb-b9561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CGHHW5lftN9lV989ofJjDD4cuebhQgk',
    appId: '1:672650725357:ios:d20b8f471d9071b06249e4',
    messagingSenderId: '672650725357',
    projectId: 'esp32-rtdb-b9561',
    databaseURL: 'https://esp32-rtdb-b9561-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-rtdb-b9561.appspot.com',
    iosBundleId: 'com.example.gmCarLocationDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CGHHW5lftN9lV989ofJjDD4cuebhQgk',
    appId: '1:672650725357:ios:d20b8f471d9071b06249e4',
    messagingSenderId: '672650725357',
    projectId: 'esp32-rtdb-b9561',
    databaseURL: 'https://esp32-rtdb-b9561-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-rtdb-b9561.appspot.com',
    iosBundleId: 'com.example.gmCarLocationDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOFSVSq7bTsSHhTldoWpp4pMpJbv_vCUk',
    appId: '1:672650725357:web:8bbf67c5fd27b9646249e4',
    messagingSenderId: '672650725357',
    projectId: 'esp32-rtdb-b9561',
    authDomain: 'esp32-rtdb-b9561.firebaseapp.com',
    databaseURL: 'https://esp32-rtdb-b9561-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-rtdb-b9561.appspot.com',
  );
}
